[package]
name = "cherrytree"
version = "0.1.0"
edition = "2021"
description = "A small, simple, and correct tree implementation."
repository = "https://github.com/raunakab/cherrytree"
license-file = "LICENSE-BSD-3-CLAUSE"

[dependencies]
slotmap = "1.0.6"
indexmap = "2.0.0"
