[package]
name = "tinytree"
version = "0.1.0"
edition = "2021"
description = "A tiny tree implementation"
repository = "https://github.com/raunakab/tinytree"
license-file = "LICENSE-BSD-3-CLAUSE"

[dependencies]
slotmap = "1.0.6"
indexmap = "2.0.0"

[features]
decl_tree = []
