[package]
name = "pettree"
version = "0.1.0"
edition = "2021"
description = "A small, simple, and correct tree implementation."
repository = "https://github.com/raunakab/pettree"

[dependencies]
petgraph = "0.6.3"
slotmap = "1.0.6"
