# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
imports_layout = "Vertical"

# Comments
wrap_comments = true
format_code_in_doc_comments = true

# Braces
control_brace_style = "ClosingNextLine"
