name: Assert Branch Naming Convention

on:
  pull_request

jobs:
  naming-rules:
    runs-on: ubuntu-latest

    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: /(feature|hotfix)\/\w*/gm
          ignore: master
